version: "3.9"

services:
  web:
    build: .
    container_name: django_gunicorn
    ports:
      
      - "8000:8000"
    volumes:
    - .:/app
    command: gunicorn revetas.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
    - .env