# Generated by Django 5.1.6 on 2025-03-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receta',
            name='favs',
            field=models.BooleanField(default=False),
        ),
    ]
