# Generated by Django 5.2.4 on 2025-07-17 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_login.usuario'),
            preserve_default=False,
        ),
    ]
