# Generated by Django 5.2.4 on 2025-07-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_valoracion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='puntaje',
            field=models.IntegerField(),
        ),
    ]
