# Generated by Django 5.2.4 on 2025-07-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_valoracion_puntaje'),
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaCocinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.receta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.usuario')),
            ],
        ),
    ]
