# Generated by Django 5.1.6 on 2025-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_carrito_categoria_ingrediente_receta_date_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='coccion',
            field=models.IntegerField(default=0),
        ),
    ]
