# Generated by Django 5.1.6 on 2025-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_receta_coccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_image/'),
        ),
    ]
