# Generated by Django 5.2.4 on 2025-08-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_recetacocinada'),
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('comprada', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(max_length=50)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.listacompra')),
            ],
        ),
    ]
