# Generated by Django 5.2.2 on 2025-06-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_receta_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetaingrediente',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='nombre',
            field=models.CharField(default='Ingrediente', max_length=255),
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='unidad',
            field=models.CharField(default='unidad', max_length=50),
        ),
    ]
