# Generated by Django 5.2.2 on 2025-06-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_recetaingrediente_ingrediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='tasks.receta'),
        ),
    ]
