# Generated by Django 5.2.2 on 2025-06-16 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_recetaingrediente_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='tasks.categoria'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tasks.receta'),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='unidad',
            field=models.CharField(max_length=50),
        ),
    ]
